name: Fundación CoMunidad
favicon: null
layout_spectrum: 0.4991
typography_spectrum: 0.50812
title: Fundación CoMunidad
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#643706'
    - '#00a9df'
    - '#f7b400'
    - '#cc0610'
    - '#000000'
  brandStrength: 0
  lightness: 0.12057433882728219
  saturation: 0.25
  rhythmicContrast: 0.8098686449229717
purpose: []
