name: Fundación CoMunidad
favicon: null
layout_spectrum: 0.4991
typography_spectrum: 0.50812
title: Fundación CoMunidad
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#643706'
    - '#00a9df'
    - '#f7b500'
    - '#cd0610'
  brandStrength: 0.2621818305924535
  lightness: 0.12057433882728219
  saturation: 0.7633912328165025
  rhythmicContrast: 0.8098686449229717
purpose: []
